name: new_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  firebase_core: ^2.16.0
  firebase_auth: ^4.10.0 
  go_router: ^11.1.2
  flutter:
    sdk: flutter  
  fireflutter:
    path: ../
  font_awesome_flutter: ^10.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
