name: fireship
description: "A lightning-fast, robust CMS for seamless real-time content management in app development."
version: 0.0.7
homepage: https://github.com/thruthesky/fireship

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  cached_network_image: ^3.3.0
  cloud_firestore: ^4.15.4
  crypto: ^3.0.3
  dio: ^5.4.0
  firebase_auth: ^4.17.4
  firebase_core: ^2.25.4
  firebase_database: ^10.4.5
  firebase_messaging: ^14.7.15
  firebase_storage: ^11.6.5
  firebase_ui_database: ^1.4.2
  flutter:
    sdk: flutter
  flutter_image_compress: ^2.1.0
  flutter_linkify: ^6.0.0
  html: ^0.15.4
  http: ^1.1.2
  image_picker: ^1.0.5
  intl: ^0.18.1
  linkify: ^5.0.0
  material_color_utilities: ^0.5.0
  rxdart: ^0.27.7
  shared_preferences: ^2.2.2
  typesense: ^0.4.0
  url_launcher: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
